refactored the follower.py and created post class
JosephMezza/SOEN341 pull request #42
Opened 2021-02-24 01:31 UTC by alexbara2000

I created the class post that will store the info for each post like the user, image, likes, comments and ID. 
refactored the follower class to be independent of the database we use.

#37 #39

2021-02-24 01:39 UTC, LiamBurchellReyes commented on posts.py
> +def addpost(user, imgpath):
Capitalization: try "addPost" instead?

2021-02-24 01:43 UTC, LiamBurchellReyes requested changes
Small change: Just fix the capitalization on the addpost function to lowerCamelCase. Excellent otherwise. Good refactor.

2021-02-24 02:04 UTC, LiamBurchellReyes approved these changes
Excellent.

2021-02-25 16:51 UTC, MatteoGisondi approved these changes
Many additions changed in synchronization branch.

2021-02-25 21:32 UTC, closed without merging